const translations = {
    en: {
        PASSWORD_GENERATOR: "PASSWORD GENERATOR",
        Language: "Language",
        Advises: "Advises",
        aboutUs: "About Us",
        lengthLabel: "Length:",
        strengthMedium: "MEDIUM",
        strengthWeak: "WEAK",
        strengthStrong: "STRONG",
        Uppercase: "Uppercase (A-Z)",
        Lowercase: "Lowercase (a-z)",
        Numbers :"Numbers (0-9)",
        Symbols: "Symbols (!@#$)",
        GENERATE_PASSWORD: "GENERATE PASSWORD",
        PASSWORD_STRENGTH_METER: "PASSWORD STRENGTH METER",
        alot: "A strong password contains a mix of uppercase and lowercase letters, numbers, and symbols. The longer your password, the stronger it becomes. We recommend using at least 16 characters.",
        Your_password_strength_is: "Your password strength is               ",
        Weak: "Weak",
        Strong: "Strong",
        Medium: "Medium",
        KNOW_OUR_MISSION:"KNOW OUR MISSION",
        mission:"The mission of creating this page is to help raise awareness about digital security. In today's world, we live online, and if we don't want to know how every technology works, it's best to have a strong password that can withstand any attack, whether it's a direct attack or a targeted attack.",
        mission1:"Many times when creating or recovering a password, we have no idea what to put, so we repeat the same password on all our accounts the same one we created with our first email. Even though you think your password is strong, it would take software a few seconds to figure it out.",
        mission2: "If you feel that someone is connecting to your internet, if your ex-partner had access to your account, if you have the same password on all your accounts, change your password.",
        mission3: "Remember that no system is perfect or invulnerable. Don't make it easy for thieves and change your password every 3 months.",
        Contact_me: "CONTACT US",
        CONTACT_TEXT: "",
        click_on: "Click on any icon to visit my network profile",
        HOW_OT_USE_IT: "HOW OT USE IT",
        First: "First, On the main page, select the password length you need.",
        Second: "Second, activate or deactivate the characters you need",
        Three: "Three, Click on the 'GENERATE PASSWORD' button",
        Four: "Four, Copy the password and paste it into the account where you are going to change the password.",
        Fifth: "Fifth, take a screenshot of the password and write on it the account where the change was applied or write it on a piece of paper where only you know where it is.",
        Empowering: "Empowering businesses through innovative solutions since 2025. We're committed to excellence in everything we do.",
        Quick_Links: "Quick Links",
        Legal: "Legal",
        Privacy: "Privacy Policy",
        Terms: "Terms of Use",
        GDPR: "GDPR Compliance",
        All_rights_reserved: "2025 SpeedPassword. All rights reserved.",
        Contact_us: "Contact Us",
        still: "we are working in this seccion",

    },
    es: {
        PASSWORD_GENERATOR: "GENERADORA DE CONTRASEÑA",
        Language: "Idioma",
        Advises: "Asesoramiento",
        aboutUs: "Sobre nosotros",
        lengthLabel: "Longitud:",
        strengthMedium: "MEDIO",
        strengthWeak: "DÉBIL",
        strengthStrong: "FUERTE",
        Uppercase: "Mayúscula (A-Z)",
        Lowercase: "Minúscula (a-z)",
        Numbers :"Números (0-9)",
        Symbols: "Símbolos (!@#$)",
        GENERATE_PASSWORD: "GENERADORA DE CONTRASEÑA",
        PASSWORD_STRENGTH_METER: "Medidor de fuerza de contraseña",
        alot: "Una contraseña segura contiene una combinación de letras, números y símbolos en minúsculas y minúsculas. Cuanto más larga sea su contraseña, más fuerte será. Recomendamos usar al menos 16 caracteres.",
        Your_password_strength_is: "Su fuerza de contraseña es               ",
        Weak: "DÉBIL",
        Strong: "FUERTE",
        Medium: "MEDIO",
        KNOW_OUR_MISSION:"Conozca nuestra misión",
        mission:"La misión de crear esta página es ayudar a crear conciencia sobre la seguridad digital. En el mundo de hoy, vivimos en línea, y si no queremos saber cómo funciona cada tecnología, es mejor tener una contraseña segura que pueda resistir cualquier ataque, ya sea un ataque directo o un ataque objetivo.",
        mission1:"Muchas veces, al crear o recuperar una contraseña, no tenemos idea de qué poner, por lo que repitemos la misma contraseña en todas nuestras cuentas, la misma que creamos con nuestro primer correo electrónico. Aunque cree que su contraseña es fuerte, se necesitaría software unos segundos para resolverla.",
        mission2: "Si cree que alguien se está conectando a su Internet, si su ex pareja tenía acceso a su cuenta, si tiene la misma contraseña en todas sus cuentas, cambie su contraseña.",
        mission3: "Recuerde que ningún sistema es perfecto o invulnerable. No sea fácil para los ladrones y cambie su contraseña cada 3 meses.",
        Contact_me: "CONTÁCTENOS",
        CONTACT_TEXT: "",
        click_on: "Haga clic en cualquier icono para visitar mi perfil de Linkdin o Youtube",
        HOW_OT_USE_IT: "COMO USARLO",
        First: "Primero, en la página principal, seleccione la longitud de la contraseña que necesita.",
        Second: "Segundo, active o desactive los caracteres que necesita",
        Three: "Tres, haga clic en el botón 'GENERAR CONTRASEÑA'",
        Four: "Cuatro, copie la contraseña y péguela en la cuenta donde va a cambiar la contraseña.",
        Fifth: "Quinto, tome una captura de pantalla de la contraseña y escriba en ella la cuenta donde se aplicó el cambio o escríbelo en una hoja de papel donde solo usted sabe dónde está.",
        Empowering: "Empoderar a las empresas a través de soluciones innovadoras desde 2025. Estamos comprometidos con la excelencia en todo lo que hacemos.",
        Quick_Links: "Links Rapidos",
        Legal: "Legal",
        Privacy: "Politica de Privacidad",
        Terms: "Terminos de uso",
        GDPR: "Cumplimiento GDPR",
        All_rights_reserved: "2025 SpeedPassword. Reservados todos los derechos.",
        Contact_us: "Contactanos",
        still: "we are working in this seccion",
    },
    fr: {
        PASSWORD_GENERATOR: "GÉNÉRATEUR DE MOT DE PASSE",
        Language: "Langue",
        Advises: "Conseils",
        aboutUs: "À Propos de Nous",
        lengthLabel: "Longueur :",
        strengthMedium: "MOYEN",
        strengthWeak: "FAIBLE",
        strengthStrong: "FORT",
        Uppercase: "Majuscules (A-Z)",
        Lowercase: "Minuscules (a-z)",
        Numbers: "Nombres (0-9)",
        Symbols: "Symboles (!@#$)",
        GENERATE_PASSWORD: "GÉNÉRER UN MOT DE PASSE",
        PASSWORD_STRENGTH_METER: "MÉTRE DE FORCE DU MOT DE PASSE",
        alot: "Un mot de passe fort contient un mélange de lettres majuscules et minuscules, de chiffres et de symboles. Plus votre mot de passe est long, plus il devient fort. Nous recommandons d'utiliser au moins 16 caractères.",
        Your_password_strength_is: "La force de votre mot de passe est ",
        Weak: "Faible",
        Strong: "Fort",
        Medium: "Moyen",
        KNOW_OUR_MISSION: "CONNAÎTRE NOTRE MISSION",
        mission: "La mission de créer cette page est d'aider à sensibiliser à la sécurité numérique. Dans le monde d'aujourd'hui, nous vivons en ligne, et si nous ne voulons pas savoir comment chaque technologie fonctionne, il est préférable d'avoir un mot de passe fort qui peut résister à toute attaque, qu'il s'agisse d'une attaque directe ou ciblée.",
        mission1: "Souvent, lors de la création ou de la récupération d'un mot de passe, nous n'avons aucune idée de ce qu'il faut mettre, alors nous répétons le même mot de passe sur tous nos comptes, celui que nous avons créé avec notre premier courriel. Même si vous pensez que votre mot de passe est fort, un logiciel mettrait quelques secondes à le découvrir.",
        mission2: "Si vous sentez que quelqu'un se connecte à votre internet, si votre ex-partenaire avait accès à votre compte, si vous avez le même mot de passe sur tous vos comptes, changez votre mot de passe.",
        mission3: "Rappelez-vous qu'aucun système n'est parfait ou invulnérable. Ne facilitez pas la tâche aux voleurs et changez votre mot de passe tous les 3 mois.",
        Contact_me: "CONTACTEZ-NOUS",
        CONTACT_TEXT: "",
        click_on: "Cliquez sur n'importe quelle icône pour visiter mon profil sur le réseau",
        HOW_OT_USE_IT: "COMMENT L'UTILISER",
        First: "D'abord, sur la page principale, sélectionnez la longueur de mot de passe dont vous avez besoin.",
        Second: "Deuxièmement, activez ou désactivez les caractères dont vous avez besoin",
        Three: "Troisièmement, cliquez sur le bouton 'GÉNÉRER UN MOT DE PASSE'",
        Four: "Quatre, copiez le mot de passe et collez-le dans le compte où vous allez changer le mot de passe.",
        Fifth: "Cinquièmement, prenez une capture d'écran du mot de passe et écrivez dessus le compte où le changement a été appliqué ou écrivez-le sur un morceau de papier où vous seul savez où il se trouve.",
        Empowering: "Autonomiser les entreprises grâce à des solutions innovantes depuis 2025. Nous nous engageons à l'excellence dans tout ce que nous faisons.",
        Quick_Links: "Liens Rapides",
        Legal: "Légal",
        Privacy: "Politique de Confidentialité",
        Terms: "Conditions d'Utilisation",
        GDPR: "Conformité au RGPD",
        All_rights_reserved: "2025 SpeedPassword. Tous droits réservés.",
        Contact_us: "Contactez-nous",
        still: "we are working in this seccion",
    },
    
    de: {
        PASSWORD_GENERATOR: "PASSWORT GENERATOR",
        Language: "Sprache",
        Advises: "Ratschläge",
        aboutUs: "Über Uns",
        lengthLabel: "Länge:",
        strengthMedium: "MITTEL",
        strengthWeak: "SCHWACH",
        strengthStrong: "STARK",
        Uppercase: "Großbuchstaben (A-Z)",
        Lowercase: "Kleinbuchstaben (a-z)",
        Numbers: "Zahlen (0-9)",
        Symbols: "Symbole (!@#$)",
        GENERATE_PASSWORD: "PASSWORT GENERIEREN",
        PASSWORD_STRENGTH_METER: "PASSWORTSTÄRKE-MESSGERÄT",
        alot: "Ein starkes Passwort enthält eine Mischung aus Groß- und Kleinbuchstaben, Zahlen und Symbolen. Je länger Ihr Passwort ist, desto stärker wird es. Wir empfehlen, mindestens 16 Zeichen zu verwenden.",
        Your_password_strength_is: "Die Stärke Ihres Passworts ist ",
        Weak: "Schwach",
        Strong: "Stark",
        Medium: "Mittel",
        KNOW_OUR_MISSION: "KENNE UNSERE MISSION",
        mission: "Die Mission dieser Seite ist es, das Bewusstsein für digitale Sicherheit zu schärfen. In der heutigen Welt leben wir online, und wenn wir nicht wissen wollen, wie jede Technologie funktioniert, ist es am besten, ein starkes Passwort zu haben, das jedem Angriff standhalten kann, sei es ein direkter oder gezielter Angriff.",
        mission1: "Oft haben wir beim Erstellen oder Wiederherstellen eines Passworts keine Ahnung, was wir eingeben sollen, also wiederholen wir dasselbe Passwort für all unsere Konten, das wir mit unserer ersten E-Mail erstellt haben. Auch wenn Sie denken, dass Ihr Passwort stark ist, würde es Software nur wenige Sekunden kosten, es herauszufinden.",
        mission2: "Wenn Sie das Gefühl haben, dass sich jemand mit Ihrem Internet verbindet, wenn Ihr Ex-Partner Zugang zu Ihrem Konto hatte, wenn Sie dasselbe Passwort für all Ihre Konten haben, ändern Sie Ihr Passwort.",
        mission3: "Denken Sie daran, dass kein System perfekt oder unverwundbar ist. Machen Sie es Dieben nicht leicht und ändern Sie Ihr Passwort alle 3 Monate.",
        Contact_me: "KONTAKTIEREN SIE UNS",
        CONTACT_TEXT: "",
        click_on: "Klicken Sie auf ein beliebiges Symbol, um mein Netzwerkprofil zu besuchen",
        HOW_OT_USE_IT: "WIE MAN ES BENUTZT",
        First: "Zuerst, wählen Sie auf der Hauptseite die benötigte Passwortlänge aus.",
        Second: "Zweitens, aktivieren oder deaktivieren Sie die benötigten Zeichen",
        Three: "Drittens, klicken Sie auf die Schaltfläche 'PASSWORT GENERIEREN'",
        Four: "Viertens, kopieren Sie das Passwort und fügen Sie es in das Konto ein, in dem Sie das Passwort ändern möchten.",
        Fifth: "Fünftens, machen Sie einen Screenshot des Passworts und notieren Sie darauf das Konto, in dem die Änderung vorgenommen wurde, oder schreiben Sie es auf ein Stück Papier, wo nur Sie wissen, wo es ist.",
        Empowering: "Unternehmen durch innovative Lösungen seit 2025 stärken. Wir verpflichten uns zu Exzellenz in allem, was wir tun.",
        Quick_Links: "Schnellzugriffe",
        Legal: "Rechtliches",
        Privacy: "Datenschutzrichtlinie",
        Terms: "Nutzungsbedingungen",
        GDPR: "DSGVO-Konformität",
        All_rights_reserved: "2025 SpeedPassword. Alle Rechte vorbehalten.",
        Contact_us: "Kontaktieren Sie uns",
        still: "we are working in this seccion",
    },

    po: {
        PASSWORD_GENERATOR: "GERADOR DE SENHAS",
        Language: "Idioma",
        Advises: "Conselhos",
        aboutUs: "Sobre Nós",
        lengthLabel: "Comprimento:",
        strengthMedium: "MÉDIO",
        strengthWeak: "FRACO",
        strengthStrong: "FORTE",
        Uppercase: "Maiúsculas (A-Z)",
        Lowercase: "Minúsculas (a-z)",
        Numbers: "Números (0-9)",
        Symbols: "Símbolos (!@#$)",
        GENERATE_PASSWORD: "GERAR SENHA",
        PASSWORD_STRENGTH_METER: "MEDIDOR DE FORÇA DA SENHA",
        alot: "Uma senha forte contém uma mistura de letras maiúsculas e minúsculas, números e símbolos. Quanto mais longa for a sua senha, mais forte ela se torna. Recomendamos usar pelo menos 16 caracteres.",
        Your_password_strength_is: "A força da sua senha é ",
        Weak: "Fraco",
        Strong: "Forte",
        Medium: "Médio",
        KNOW_OUR_MISSION: "CONHEÇA NOSSA MISSÃO",
        mission: "A missão de criar esta página é ajudar a aumentar a conscientização sobre segurança digital. No mundo de hoje, vivemos online, e se não quisermos saber como cada tecnologia funciona, é melhor ter uma senha forte que possa resistir a qualquer ataque, seja um ataque direto ou direcionado.",
        mission1: "Muitas vezes, ao criar ou recuperar uma senha, não temos ideia do que colocar, então repetimos a mesma senha em todas as nossas contas, a mesma que criamos com nosso primeiro e-mail. Mesmo que você ache que sua senha é forte, um software levaria apenas alguns segundos para descobri-la.",
        mission2: "Se você sentir que alguém está se conectando à sua internet, se seu ex-parceiro teve acesso à sua conta, se você tem a mesma senha em todas as suas contas, mude sua senha.",
        mission3: "Lembre-se de que nenhum sistema é perfeito ou invulnerável. Não facilite a vida dos ladrões e mude sua senha a cada 3 meses.",
        Contact_me: "CONTATE-NOS",
        CONTACT_TEXT: "",
        click_on: "Clique em qualquer ícone para visitar meu perfil na rede",
        HOW_OT_USE_IT: "COMO USÁ-LO",
        First: "Primeiro, na página principal, selecione o comprimento de senha que você precisa.",
        Second: "Segundo, ative ou desative os caracteres que você precisa",
        Three: "Terceiro, clique no botão 'GERAR SENHA'",
        Four: "Quarto, copie a senha e cole-a na conta onde você vai mudar a senha.",
        Fifth: "Quinto, tire uma captura de tela da senha e escreva nela a conta onde a mudança foi aplicada ou escreva em um pedaço de papel onde apenas você sabe onde está.",
        Empowering: "Empoderando empresas por meio de soluções inovadoras desde 2025. Estamos comprometidos com a excelência em tudo o que fazemos.",
        Quick_Links: "Links Rápidos",
        Legal: "Legal",
        Privacy: "Política de Privacidade",
        Terms: "Termos de Uso",
        GDPR: "Conformidade com o GDPR",
        All_rights_reserved: "2025 SpeedPassword. Todos os direitos reservados.",
        Contact_us: "Entre em Contato Conosco",
        still: "we are working in this seccion",
    },

    bin: {
        PASSWORD_GENERATOR: "GENERATOR KATA SANDI",
        Language: "Bahasa",
        Advises: "Saran",
        aboutUs: "Tentang Kami",
        lengthLabel: "Panjang:",
        strengthMedium: "SEDANG",
        strengthWeak: "LEMAH",
        strengthStrong: "KUAT",
        Uppercase: "Huruf Besar (A-Z)",
        Lowercase: "Huruf Kecil (a-z)",
        Numbers: "Angka (0-9)",
        Symbols: "Simbol (!@#$)",
        GENERATE_PASSWORD: "GENERATE KATA SANDI",
        PASSWORD_STRENGTH_METER: "METER KEKUATAN KATA SANDI",
        alot: "Kata sandi yang kuat mengandung campuran huruf besar dan kecil, angka, dan simbol. Semakin panjang kata sandi Anda, semakin kuat. Kami merekomendasikan untuk menggunakan setidaknya 16 karakter.",
        Your_password_strength_is: "Kekuatan kata sandi Anda adalah ",
        Weak: "Lemah",
        Strong: "Kuat",
        Medium: "Sedang",
        KNOW_OUR_MISSION: "KENALI MISI KAMI",
        mission: "Misi dari pembuatan halaman ini adalah untuk membantu meningkatkan kesadaran tentang keamanan digital. Di dunia saat ini, kita hidup online, dan jika kita tidak ingin tahu bagaimana setiap teknologi bekerja, sebaiknya memiliki kata sandi yang kuat yang dapat menahan serangan apa pun, baik itu serangan langsung atau serangan yang ditargetkan.",
        mission1: "Sering kali saat membuat atau memulihkan kata sandi, kita tidak tahu apa yang harus dimasukkan, jadi kita mengulangi kata sandi yang sama di semua akun kita, yang sama yang kita buat dengan email pertama kita. Meskipun Anda berpikir kata sandi Anda kuat, perangkat lunak hanya akan membutuhkan beberapa detik untuk mengetahuinya.",
        mission2: "Jika Anda merasa ada yang terhubung ke internet Anda, jika mantan pasangan Anda memiliki akses ke akun Anda, jika Anda memiliki kata sandi yang sama di semua akun Anda, ubah kata sandi Anda.",
        mission3: "Ingatlah bahwa tidak ada sistem yang sempurna atau tidak dapat ditembus. Jangan memudahkan pencuri dan ubah kata sandi Anda setiap 3 bulan.",
        Contact_me: "HUBUNGI KAMI",
        CONTACT_TEXT: "",
        click_on: "Klik pada ikon mana pun untuk mengunjungi profil jaringan saya",
        HOW_OT_USE_IT: "BAGAIMANA MENGGUNAKANNYA",
        First: "Pertama, di halaman utama, pilih panjang kata sandi yang Anda butuhkan.",
        Second: "Kedua, aktifkan atau nonaktifkan karakter yang Anda butuhkan",
        Three: "Ketiga, klik tombol 'GENERATE KATA SANDI'",
        Four: "Keempat, salin kata sandi dan tempelkan ke akun di mana Anda akan mengubah kata sandi.",
        Fifth: "Kelima, ambil tangkapan layar kata sandi dan tuliskan di atasnya akun di mana perubahan diterapkan atau tuliskan di selembar kertas di mana hanya Anda yang tahu di mana itu.",
        Empowering: "Memberdayakan bisnis melalui solusi inovatif sejak 2025. Kami berkomitmen untuk keunggulan dalam segala hal yang kami lakukan.",
        Quick_Links: "Tautan Cepat",
        Legal: "Hukum",
        Privacy: "Kebijakan Privasi",
        Terms: "Syarat Penggunaan",
        GDPR: "Kepatuhan GDPR",
        All_rights_reserved: "2025 SpeedPassword. Semua hak dilindungi.",
        Contact_us: "Hubungi Kami",
        still: "we are working in this seccion",
    },

    ph: {
        PASSWORD_GENERATOR: "GENERATOR NG PASSWORD",
        Language: "Wika",
        Advises: "Mga Payo",
        aboutUs: "Tungkol sa Amin",
        lengthLabel: "Haba:",
        strengthMedium: "MEDYO",
        strengthWeak: "MAHINA",
        strengthStrong: "MATIBAY",
        Uppercase: "Malalaking Titik (A-Z)",
        Lowercase: "Maliliit na Titik (a-z)",
        Numbers: "Mga Numero (0-9)",
        Symbols: "Mga Simbolo (!@#$)",
        GENERATE_PASSWORD: "MAGGENERATE NG PASSWORD",
        PASSWORD_STRENGTH_METER: "METER NG KALAKASAN NG PASSWORD",
        alot: "Ang isang malakas na password ay naglalaman ng halo ng malalaking titik at maliliit na titik, mga numero, at mga simbolo. Habang mas mahaba ang iyong password, mas matibay ito. Inirerekomenda naming gumamit ng hindi bababa sa 16 na karakter.",
        Your_password_strength_is: "Ang lakas ng iyong password ay ",
        Weak: "Mahina",
        Strong: "Matibay",
        Medium: "Medyo",
        KNOW_OUR_MISSION: "ALAMIN ANG AMING MISYON",
        mission: "Ang misyon ng paglikha ng pahinang ito ay upang makatulong na itaas ang kamalayan tungkol sa digital na seguridad. Sa mundo ngayon, tayo ay namumuhay online, at kung ayaw nating malaman kung paano gumagana ang bawat teknolohiya, mas mabuti na magkaroon ng isang malakas na password na kayang tiisin ang anumang atake, maging ito ay isang direktang atake o isang nakatuong atake.",
        mission1: "Madalas, kapag gumagawa o nagbabalik ng isang password, wala tayong ideya kung ano ang ilalagay, kaya inuulit natin ang parehong password sa lahat ng ating mga account, ang parehong ginawa natin sa ating unang email. Kahit na sa tingin mo ay malakas ang iyong password, aabutin lamang ng ilang segundo para sa software na malaman ito.",
        mission2: "Kung sa tingin mo ay may kumokonekta sa iyong internet, kung ang iyong ex-partner ay may access sa iyong account, kung mayroon kang parehong password sa lahat ng iyong mga account, palitan ang iyong password.",
        mission3: "Tandaan na walang sistema ang perpekto o hindi matibay. Huwag gawing madali para sa mga magnanakaw at palitan ang iyong password tuwing 3 buwan.",
        Contact_me: "KONTAKIN KAMI",
        CONTACT_TEXT: "",
        click_on: "I-click ang anumang icon upang bisitahin ang aking profile sa network",
        HOW_OT_USE_IT: "PAANO ITO GAMITIN",
        First: "Una, sa pangunahing pahina, piliin ang haba ng password na kailangan mo.",
        Second: "Pangalawa, i-activate o i-deactivate ang mga karakter na kailangan mo",
        Three: "Pangatlo, i-click ang button na 'MAGGENERATE NG PASSWORD'",
        Four: "Pang-apat, kopyahin ang password at i-paste ito sa account kung saan mo babaguhin ang password.",
        Fifth: "Pang-lima, kumuha ng screenshot ng password at isulat dito ang account kung saan naipasa ang pagbabago o isulat ito sa isang piraso ng papel kung saan ikaw lamang ang nakakaalam kung nasaan ito.",
        Empowering: "Pagtutulungan ang mga negosyo sa pamamagitan ng mga makabagong solusyon mula 2025. Kami ay nakatuon sa kahusayan sa lahat ng aming ginagawa.",
        Quick_Links: "Mabilis na Mga Link",
        Legal: "Legal",
        Privacy: "Patakaran sa Privacy",
        Terms: "Mga Tuntunin ng Paggamit",
        GDPR: "Pagsunod sa GDPR",
        All_rights_reserved: "2025 SpeedPassword. Lahat ng karapatan ay nakalaan.",
        Contact_us: "Makipag-ugnayan sa Amin",
        still: "we are working in this seccion",
    },


};
function updateLanguage(lang) {
    const translation = translations[lang];
    document.querySelectorAll('[data-translate]').forEach(element => {
        element.textContent = translation[element.dataset.translate];
    });
}
// Initialize default language (English)
updateLanguage('en');